version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["87:e7:7f:be:57:f6:0b:b5:e8:44:f2:68:2b:79:4a:e9"] 
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --region us-east-2 \
              --template-file .circleci/files/template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - destroy_environment
        when: on_fail
workflows:
  my_workflow:
    jobs:
      - create_infrastructure